### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by arjunmenon** [koggdal/scroll-converter#4]
Hey
If the mouse is near the bottom scrollbar, but obviously inside the page, scrolling does not happen, strangely.
Only if the mouse is moved towards the content does the scrolling initiates.
Also test it by scrolling backwards from the far right of the page to the left.

Strange behavior in any case!

Thanks.

**Comment by koggdal** [comment]
Hi,

What browser and OS are you using? I think what you're seeing is the bouncy effect Chrome and Safari uses when you scroll at the edges. I can't get this to happen in Safari though, so my guess is that this is a Chromium issue. I don't think there's much I can do here I'm afraid.
