### ISSUE TITLE
Trackpad Issue

### ISSUE THREAD

**Issue by johanneslamers** [koggdal/scroll-converter#6]
Horizontal scrolling (left right direction) does not work with trackpad on a macbook.
Up & Down works perfect, but left and right not. 

Mousewheel works perfect too. Up, down, left, right. All converting in the right direction.

**Comment by koggdal** [comment]
Thanks for reporting! Should now be fixed in [1.0.2](https://github.com/koggdal/scroll-converter/blob/v1.0.2/scroll-converter.min.js) :)

**Comment by johanneslamers** [comment]
Thanks!
