### ISSUE TITLE
Console Error in Chrome

### ISSUE THREAD

**Issue by mossmoss** [koggdal/scroll-converter#8]
Scrolling works but generates a console error in Chrome: 

Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

Searching around it seems this might be fixable by changing some handler arguments -- possibly 
something like { passive: false }

**Comment by koggdal** [comment]
Thanks for the report! This is now fixed in the latest version found in the repo (1.0.3) :)

**Comment by mossmoss** [comment]
I can confirm the console error is gone! Thanks for fixing.
