### ISSUE TITLE
firefox the movement is jerky

### ISSUE THREAD

**Issue by lackmy** [koggdal/scroll-converter#9]
Hello, thanks for this js, I have a question about firefox, I have a bug on the horizontal scroll. 
on firefox the movement is jerky and not fluid? 
Do you have any idea 
thank you

**Comment by koggdal** [comment]
Hi! I updated the library to handle the standard API for wheel events, which should make it more fluid in Firefox :)

You can find the new file here: https://github.com/koggdal/scroll-converter/blob/v1.0.4/scroll-converter.min.js
